### PR TITLE
Fixed mtcp doesn't notify onvm to reclaim resource when a mtcp based …

### PR DESCRIPTION
**Pull request by lyuxiaosu**
…process exits

### CODE REVIEW

**Comment by lyuxiaosu** [comment]
A mtcp based application should call onvm's interface to notify onvm when it exits

**Comment by lyuxiaosu** [comment]
@koolzz please review

**Comment by koolzz** [comment]
@lyuxiaosu Good catch, this should fix bad cleanup. The only thing I'm not sure if it needs the extra dpdk logic. I think it waits for other cores above your fix? We should probably just call nflib stop and return, I'll take a look later.

**Comment by ajamshed** [comment]
Please re-submit the PR to the `devel` branch. I will immediately merge the request.

**Comment by lyuxiaosu** [comment]
@ajamshed OK, I am doing that

**Comment by ajamshed** [comment]
By the way, I just found out mTCP `devel` branch's compilation is breaking with the recent addition of CCP module. I am currently fixing it. Will let you know once it is stable soon.

**Comment by lyuxiaosu** [comment]
@ajamshed OK, I will re-submit after you fix it

**Comment by ajamshed** [comment]
@lyuxiaosu ,

Please go ahead and resubmit the patch to the `devel` branch.

**Comment by lyuxiaosu** [comment]
@ajamshed I updated the code and did the same modification based on the latest code, then submitted another pull request to devel branch. I am not familiar about this, please let me know if I did the wrong operations, or if I just need to submit the old branch to the devel without needing to generate another branch.

**Comment by ajamshed** [comment]
All good! I have merged your PR in the `devel` branch. Thanks. Sorry for the delay.

**Pull request closed without merging**
